sudo: required
service: 
  - docker

befor_install:
  - docker build -t insonusk/hard-work-service-test -f ./HardWorkService/Dockerfile.test ./HardWorkService

script:
  - docker run insonusk/hard-work-service-test dotnet test

deploy:
  provider: script
  script: bash Scripts/docker-build-release-push.sh
  on: 
    branch: master