sudo: required
service: 
  - docker

befor_install:
  - docker build -t insonusk/hard-work-service -f ./HardWorkService/Dockerfile.test ./HardWorkService

script:
  - docker run insonusk/hard-work-service dotnet test

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master